# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a75tfgg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/MSI-Work/myip/MJ_inputclk_DS_GBUF/MJ_inputclk_DS_GBUF.cache/wt [current_project]
set_property parent.project_path F:/MSI-Work/myip/MJ_inputclk_DS_GBUF/MJ_inputclk_DS_GBUF.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/MSI-Work/myip/MJ_inputclk_DS_GBUF/MJ_inputclk_DS_GBUF.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib F:/MSI-Work/myip/MJ_inputclk_DS_GBUF/MJ_inputclk_DS_GBUF.srcs/sources_1/new/MJ_inputclk_ds_gbuf.v
synth_design -top MJ_inputclk_ds_gbuf -part xc7a75tfgg484-2
write_checkpoint -noxdef MJ_inputclk_ds_gbuf.dcp
catch { report_utilization -file MJ_inputclk_ds_gbuf_utilization_synth.rpt -pb MJ_inputclk_ds_gbuf_utilization_synth.pb }
