# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a75tfgg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/MSI-Work/myip/MJ_IBUFG_DS/MJ_IBUFG_DS.cache/wt [current_project]
set_property parent.project_path F:/MSI-Work/myip/MJ_IBUFG_DS/MJ_IBUFG_DS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/MSI-Work/myip/MJ_IBUFG_DS/MJ_IBUFG_DS.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib F:/MSI-Work/myip/MJ_IBUFG_DS/MJ_IBUFG_DS.srcs/sources_1/new/MJ_IBUFG_DS.v
synth_design -top MJ_IBUFG_DS -part xc7a75tfgg484-2
write_checkpoint -noxdef MJ_IBUFG_DS.dcp
catch { report_utilization -file MJ_IBUFG_DS_utilization_synth.rpt -pb MJ_IBUFG_DS_utilization_synth.pb }
