webtalk_init -webtalk_dir D:/Git/spline/DAQ_Z30/DAQ_Z30.sim/sim_1/behav/xsim/xsim.dir/tb_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 29 23:42:44 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ac60ca53-ee1f-494c-83db-200ffd805f52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3cc06c5e03384bc6bf530efbc77b3433" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "81" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 9950X 16-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "66.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5385465 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15844_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1623235038 -regid "" -xml D:/Git/spline/DAQ_Z30/DAQ_Z30.sim/sim_1/behav/xsim/xsim.dir/tb_test_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Git/spline/DAQ_Z30/DAQ_Z30.sim/sim_1/behav/xsim/xsim.dir/tb_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Git/spline/DAQ_Z30/DAQ_Z30.sim/sim_1/behav/xsim/xsim.dir/tb_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
