# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a75tfgg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/MSI-Work/myip/mj_not/mj_not.cache/wt [current_project]
set_property parent.project_path F:/MSI-Work/myip/mj_not/mj_not.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib F:/MSI-Work/myip/mj_not/mj_not.srcs/sources_1/new/mj_not.v
synth_design -top mj_not -part xc7a75tfgg484-2
write_checkpoint -noxdef mj_not.dcp
catch { report_utilization -file mj_not_utilization_synth.rpt -pb mj_not_utilization_synth.pb }
