# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z030ffg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/MSI-Work/myip/Decode_ADS4249/Decode_ADS4249.cache/wt [current_project]
set_property parent.project_path F:/MSI-Work/myip/Decode_ADS4249/Decode_ADS4249.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/MSI-Work/myip/Decode_ADS4249/Decode_ADS4249.srcs/sources_1/imports/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib F:/MSI-Work/myip/Decode_ADS4249/Decode_ADS4249.srcs/sources_1/imports/new/ADS4249_Decode.v
synth_design -top ADS4249_Decode -part xc7z030ffg676-2
write_checkpoint -noxdef ADS4249_Decode.dcp
catch { report_utilization -file ADS4249_Decode_utilization_synth.rpt -pb ADS4249_Decode_utilization_synth.pb }
